### ISSUE TITLE
Thank you for making this addon but this is a Google issue

### ISSUE THREAD

**Issue by andreicristianpetcu** [JonathanNakandala/Chrome-UA-for-Firefox-Android-on-Google#1]
Thank you for making this addon but this is a Google issue, not a Firefox issue.

I reported a bug in [WebCompat](https://webcompat.com/issues/5413). You can also view [the same bug in Github](https://github.com/webcompat/web-bugs/issues/5413).

I guess you might be interested in following this bug so this is not an actual bug report for your addon :)

**Comment by JonathanNakandala** [comment]
Yeah, it's totally a Google issue and thanks for the link.
I made this to use until Google decides to stop sending the 'lite' version of their search results to Firefox Android.
